name: CI

on:
  workflow_dispatch:

permissions:
  contents: write

jobs:
  build-kernel:
    name: Build Kernel
    runs-on: ubuntu-22.04
    steps:
      - name: Build
        uses: dabao1955/kernel_build_action@main
        with:
          kernel-url: https://github.com/oppo-source/android_kernel_4.14_oppo_mtk5g.git
          kernel-branch: oppo/mtk_s_12.1
          config: k6853v1_64_defconfig
          arch: arm64
          aosp-gcc: true
          aosp-clang: true
          android-version: 12
          aosp-clang-version: r383902
          CLANG_TRIPLE := aarch64-linux-android-
          anykernel3: true
          release: true
          access-token: ${{ secrets.GITHUB_TOKEN }}
